import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("data/telemetria_simulada.csv")
# Criar figura com 2 linhas e 2 colunas de gráficos
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
# Gráfico 1: Temperatura (canto superior esquerdo)
axes[0, 0].plot(df["timestamp"], df["temperatura"], color="red")
axes[0, 0].set_title("Temperatura")
axes[0, 0].set_xlabel("Tempo (s)")
axes[0, 0].set_ylabel("°C")
axes[0, 0].grid(True, alpha=0.3)
# Gráfico 2: Pressão (canto superior direito)
axes[0, 1].plot(df["timestamp"], df["pressao"], color="blue")
axes[0, 1].set_title("Pressão")
axes[0, 1].set_xlabel("Tempo (s)")
axes[0, 1].set_ylabel("hPa")
axes[0, 1].grid(True, alpha=0.3)
# Gráfico 3: Altitude (canto inferior esquerdo)
axes[1, 0].fill_between(df["timestamp"], df["altitude"], alpha=0.3, color="green")
axes[1, 0].plot(df["timestamp"], df["altitude"], color="green")
axes[1, 0].set_title("Altitude")
axes[1, 0].set_xlabel("Tempo (s)")
axes[1, 0].set_ylabel("m")
axes[1, 0].grid(True, alpha=0.3)
# Gráfico 4: Correlação Temperatura vs Altitude (canto inferior direito)
axes[1, 1].scatter(df["altitude"], df["temperatura"], alpha=0.5, color="purple")
axes[1, 1].set_title("Temperatura vs Altitude")
axes[1, 1].set_xlabel("Altitude (m)")
axes[1, 1].set_ylabel("Temperatura (°C)")
axes[1, 1].grid(True, alpha=0.3)
# Título geral
fig.suptitle("Dashboard de Telemetria - Voo CanSat", fontsize=14, fontweight="bold")
# Ajustar espaçamento
plt.tight_layout()
plt.savefig("docs/dashboard_subplots.png", dpi=150, bbox_inches="tight")
print("Dashboard guardado em docs/dashboard_subplots.png")
plt.show()